# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

# Use --ignore-scripts to skip any installation scripts if not needed
RUN npm install --ignore-scripts

# Copy all source code
COPY . .

# Build the project
RUN npm run build

# Expose port if required, though MCP runs on stdio.

# Start the server
CMD ["node", "build/index.js"]
